#!/usr/bin/env bash
set -euo pipefail

repo="${OPENREEL_REPO:-https://github.com/yutianxiao6/openreel-studio.git}"
branch="${OPENREEL_BRANCH:-main}"
home_dir="${OPENREEL_HOME:-$HOME/openreel-studio}"

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "$1 is required. $2" >&2
    exit 1
  fi
}

need git "Install Git and run this script again."
need docker "Install Docker Engine and the Docker Compose plugin first."

use_sudo=0
if ! docker info >/dev/null 2>&1; then
  if command -v sudo >/dev/null 2>&1 && sudo -n docker info >/dev/null 2>&1; then
    use_sudo=1
  else
    echo "Docker is installed but not usable by this user." >&2
    echo "Start Docker or add the user to the docker group, then run again." >&2
    exit 1
  fi
fi

docker_cmd() {
  if [ "$use_sudo" = "1" ]; then
    sudo docker "$@"
  else
    docker "$@"
  fi
}

if ! docker_cmd compose version >/dev/null 2>&1; then
  echo "Docker Compose plugin is required. Install docker compose v2 and run again." >&2
  exit 1
fi

set_env_var() {
  file="$1"
  key="$2"
  value="$3"
  tmp="${file}.tmp.$$"
  awk -v key="$key" -v value="$value" '
    BEGIN { done = 0 }
    $0 ~ "^" key "=" {
      print key "=" value
      done = 1
      next
    }
    { print }
    END {
      if (!done) print key "=" value
    }
  ' "$file" > "$tmp"
  mv "$tmp" "$file"
}

get_env_var() {
  file="$1"
  key="$2"
  awk -F= -v key="$key" '$1 == key { value = substr($0, length(key) + 2) } END { print value }' "$file"
}

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    date +%s%N | sha256sum | awk '{print $1}'
  fi
}

prompt_password() {
  if [ -n "${OPENREEL_ADMIN_PASSWORD:-}" ]; then
    printf "%s" "$OPENREEL_ADMIN_PASSWORD"
    return
  fi
  if [ ! -r /dev/tty ]; then
    echo "Set OPENREEL_ADMIN_PASSWORD or run this script from an interactive terminal." >&2
    exit 1
  fi
  local first second
  printf "Admin password: " > /dev/tty
  stty -echo < /dev/tty
  IFS= read -r first < /dev/tty
  stty echo < /dev/tty
  printf "\nConfirm password: " > /dev/tty
  stty -echo < /dev/tty
  IFS= read -r second < /dev/tty
  stty echo < /dev/tty
  printf "\n" > /dev/tty
  if [ "$first" != "$second" ]; then
    echo "Passwords do not match." >&2
    exit 1
  fi
  if [ -z "$first" ]; then
    echo "Password cannot be empty." >&2
    exit 1
  fi
  printf "%s" "$first"
}

prompt_user() {
  if [ -n "${OPENREEL_AUTH_USER:-}" ]; then
    printf "%s" "$OPENREEL_AUTH_USER"
    return
  fi
  if [ ! -r /dev/tty ]; then
    printf "admin"
    return
  fi
  local user
  printf "Admin username [admin]: " > /dev/tty
  IFS= read -r user < /dev/tty
  printf "%s" "${user:-admin}"
}

if [ -d "$home_dir/.git" ]; then
  echo "Updating OpenReel Studio in $home_dir..."
  git -C "$home_dir" fetch origin "$branch"
  git -C "$home_dir" checkout "$branch"
  git -C "$home_dir" pull --ff-only origin "$branch"
else
  echo "Cloning OpenReel Studio to $home_dir..."
  mkdir -p "$(dirname "$home_dir")"
  git clone --branch "$branch" "$repo" "$home_dir"
fi

cd "$home_dir"

if [ ! -f .env.production ]; then
  cp .env.production.example .env.production
  chmod 600 .env.production
fi

mkdir -p \
  data \
  storage \
  assets \
  config \
  plugins \
  skills/workflows \
  skills/prompts \
  skills/review \
  workflow_templates

if [ -n "${OPENREEL_AUTH_USER:-}" ]; then
  set_env_var .env.production AUTH_USER "$OPENREEL_AUTH_USER"
elif [ -z "$(get_env_var .env.production AUTH_USER)" ]; then
  set_env_var .env.production AUTH_USER "$(prompt_user)"
fi

if [ -z "$(get_env_var .env.production AUTH_PASSWORD_HASH)" ]; then
  password="$(prompt_password)"
  password_hash="$(docker_cmd run --rm caddy:2-alpine caddy hash-password --plaintext "$password")"
  set_env_var .env.production AUTH_PASSWORD_HASH "$password_hash"
fi

if [ -z "$(get_env_var .env.production SECRET_KEY)" ]; then
  set_env_var .env.production SECRET_KEY "$(random_secret)"
fi

echo "Starting OpenReel Studio server..."
docker_cmd compose --env-file .env.production -f docker-compose.prod.yml up -d --build

port="$(get_env_var .env.production APP_PUBLIC_PORT)"
port="${port:-3100}"

cat <<EOF

OpenReel Studio is running.

URL:
  https://<your-server-ip>:${port}

Useful commands:
  cd "$home_dir"
  docker compose --env-file .env.production -f docker-compose.prod.yml ps
  docker compose --env-file .env.production -f docker-compose.prod.yml logs -f
  docker compose --env-file .env.production -f docker-compose.prod.yml down

The HTTPS certificate is generated by Caddy's internal CA, so browsers may show
a certificate warning on first visit.
EOF
